// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYYmYGuRX6LmFRvSwV_FDXgzDlDmPV3E',
    appId: '1:501600508338:web:cd0b9608d7d5606d0fecab',
    messagingSenderId: '501600508338',
    projectId: 'meal-recipes-app-f07f8',
    authDomain: 'meal-recipes-app-f07f8.firebaseapp.com',
    storageBucket: 'meal-recipes-app-f07f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARTg3QIl-5y-qy_iGVo6cu-ppgHlxYhM8',
    appId: '1:501600508338:android:4c8a46c6cddb8fcf0fecab',
    messagingSenderId: '501600508338',
    projectId: 'meal-recipes-app-f07f8',
    storageBucket: 'meal-recipes-app-f07f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPlqA7OPBWnZfLNZYWyhj9u2U6qxeylk',
    appId: '1:501600508338:ios:1e21c0d3efbe897e0fecab',
    messagingSenderId: '501600508338',
    projectId: 'meal-recipes-app-f07f8',
    storageBucket: 'meal-recipes-app-f07f8.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPlqA7OPBWnZfLNZYWyhj9u2U6qxeylk',
    appId: '1:501600508338:ios:1e21c0d3efbe897e0fecab',
    messagingSenderId: '501600508338',
    projectId: 'meal-recipes-app-f07f8',
    storageBucket: 'meal-recipes-app-f07f8.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBYYmYGuRX6LmFRvSwV_FDXgzDlDmPV3E',
    appId: '1:501600508338:web:e4691f0642db597e0fecab',
    messagingSenderId: '501600508338',
    projectId: 'meal-recipes-app-f07f8',
    authDomain: 'meal-recipes-app-f07f8.firebaseapp.com',
    storageBucket: 'meal-recipes-app-f07f8.firebasestorage.app',
  );
}
